"""new fields in user model

Revision ID: 470ea9f9253c
Revises: 2776cd84d760
Create Date: 2018-12-07 11:09:18.984268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470ea9f9253c'
down_revision = '2776cd84d760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
